import type { Metadata } from "next";
import { DM_Sans, Bitcount_Grid_Double } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const bitcountGridDouble = Bitcount_Grid_Double({
  variable: "--font-bitcount-grid-double",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${bitcountGridDouble.variable} antialiased`}
      >
        <div
          className="absolute inset-0 z-[-1]"
          style={{
            background: "radial-gradient(125% 125% at 50% 10%, #000000 40%, #010133 100%)",
          }}
        />
        {children}
      </body>
    </html>
  );
}
