import type { Metadata } from "next";
import { DM_Sans, Bitcount_Grid_Double } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/lib/provider/query-provider";
import { AuthProvider } from "@/lib/provider/auth-provider";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const bitcountGridDouble = Bitcount_Grid_Double({
  variable: "--font-bitcount-grid-double",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${bitcountGridDouble.variable} bg-black antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            {children}
            <Toaster className="font-sans" />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
