"use client";

import { toast } from "sonner";
import { Button } from "../ui/button";
import { useQuery } from "@tanstack/react-query";
import { getUserSubmissions } from "@/services/user.service";
import { useEffect, useState } from "react";
import { problemsStore } from "@/store/problems.store";
import { syncQuestions, updateQuestionDB } from "@/services/questions.service";
import { RatingToTag } from "@/lib/helper/ratingToTag";

type SyncButtonProps = {
    codeforcesId: string,
    tabValue: string,
};

const SyncButton = ({ codeforcesId, tabValue } : SyncButtonProps) => {
    const { hydrated, todaysQuestions, setTodaysQuestions } = problemsStore();
    const [userSubmissionsSet, setUserSubmissionsSet] = useState<Set<string>>(new Set());

    const { data: userSubmissions, isLoading, isRefetching, refetch } = useQuery({
        queryKey: ['userSubmissions'],
        queryFn: () => getUserSubmissions(codeforcesId),
        enabled: false,
    });

    const handleSync = async () => {
        if(tabValue === 'past') {
            toast('Sync is only available for today\'s problems.');
            return;
        }

        const res = await refetch();

        if(res.data &&
           res.data.submissions &&
           res.data.submissions.length === 0
        ) {
            toast('You haven\'t made any submissions yet.');
            return;
        }
    }

    useEffect(() => {
        if(!userSubmissions) return;

        const newSet = new Set<string>();

        userSubmissions.submissions.forEach((submission: any) => {
            if(submission.verdict === "OK") {
                const key = `${submission.problem.name}`;
                newSet.add(key);
            };
        });

        console.log("User submissions set updated:", newSet);

        setUserSubmissionsSet(newSet);
    }, [userSubmissions]);

    console.log("I am here");

    useEffect(() => {
        if(!todaysQuestions || userSubmissionsSet.size === 0) return;

        let hasChanges = false;
        const solvedQuestionsTags: string[] = [];

        const updatedTodaysQuestions = todaysQuestions.map((question) => {
            if(userSubmissionsSet.has(question.name)) {
                hasChanges = true;
                // Push the tag generated by me based on the ratings
                solvedQuestionsTags.push(RatingToTag(question.rating));
                return { ...question, solved: true };
            }
            return question;
        });

        if(!hasChanges) {
            console.log("No new solved questions to sync.");
            toast('No new solved questions to sync.');
            return;
        }

        // Immedietly send to the store, so that UI updates
        setTodaysQuestions(updatedTodaysQuestions);

        // Return if no new solved questions
        if(solvedQuestionsTags.length === 0) {
            console.log("No new solved questions to sync.");
            toast('No new solved questions to sync.');
            return;
        }

        (async () => {
            const res = await updateQuestionDB(codeforcesId, updatedTodaysQuestions, solvedQuestionsTags);

            if(!res.success) {
                toast.error(res.message || 'Failed to update questions in DB.');
            }

            else {
                // Fire and Forget to the backend
                syncQuestions(codeforcesId, updatedTodaysQuestions)
                .then((data) => {
                    toast(data.message || 'Questions synced in the background successfully.');
                })
                .catch((err) => {
                    toast(err.message ||'Failed to sync questions in the background.');
                });
            }
        })();
    },[userSubmissionsSet]);

    const isDisabled = !todaysQuestions || todaysQuestions.length === 0 || isLoading || isRefetching || !hydrated;

    return (
        <Button onClick={handleSync} disabled={isDisabled} className="cursor-pointer">
            {isLoading || isRefetching ? 'Syncing...' : 'Sync Submissions'}
        </Button>
    )
}

export default SyncButton;